---
cook.special: cook78
---
spring:
  config
    activate:
      on-profile: development
  
cook.special: cook100-development

---
spring:
  config
    activate:
      on-profile: dev1
  
cook.special: cook100-dev1

